services:
  accounts:
    image: "galatex/accounts:1.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank
  loans:
    image: "galatex/loans:1.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank
  cards:
    image: "galatex/cards:1.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank
networks:
  eazyBank:
    driver: "bridge"